//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تفعيل الدور بنجاح.
        /// </summary>
        public static string ActivatingRoleSucceeded {
            get {
                return ResourceManager.GetString("ActivatingRoleSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تفعيل المستخدم بنجاح.
        /// </summary>
        public static string ActivatingUserSucceeded {
            get {
                return ResourceManager.GetString("ActivatingUserSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفعل.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة رد.
        /// </summary>
        public static string AddReply {
            get {
                return ResourceManager.GetString("AddReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنبيه.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع التذاكر.
        /// </summary>
        public static string AllTickets {
            get {
                return ResourceManager.GetString("AllTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشاط.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين الصلاحيات.
        /// </summary>
        public static string AssignClaims {
            get {
                return ResourceManager.GetString("AssignClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بواسطة.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار دور.
        /// </summary>
        public static string ChooseRole_Required {
            get {
                return ResourceManager.GetString("ChooseRole_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات.
        /// </summary>
        public static string Claims {
            get {
                return ResourceManager.GetString("Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضغط على.
        /// </summary>
        public static string ClickOn {
            get {
                return ResourceManager.GetString("ClickOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستكمال التسجيل.
        /// </summary>
        public static string CompleteRegistration {
            get {
                return ResourceManager.GetString("CompleteRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إستكمال التسجيل بنجاح.
        /// </summary>
        public static string CompleteRegistrationSucceeded {
            get {
                return ResourceManager.GetString("CompleteRegistrationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواصل معنا.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحتوي على الأقل رقم.
        /// </summary>
        public static string ContainAtLeastOneDigit {
            get {
                return ResourceManager.GetString("ContainAtLeastOneDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحتوي على الأقل حرف.
        /// </summary>
        public static string ContainAtLeastOneLetter {
            get {
                return ResourceManager.GetString("ContainAtLeastOneLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على المحتوى.
        /// </summary>
        public static string ContentNotFound {
            get {
                return ResourceManager.GetString("ContentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاء.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء حساب.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء إنشاء التذكرة ، يرجى المحاولة مرة أخرى.
        /// </summary>
        public static string CreateTicketFailure {
            get {
                return ResourceManager.GetString("CreateTicketFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاء تذكرة دعم فني بنجاح.
        /// </summary>
        public static string CreateTicketSucceeded {
            get {
                return ResourceManager.GetString("CreateTicketSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الدور بنجاح.
        /// </summary>
        public static string DeleteRoleSucceeded {
            get {
                return ResourceManager.GetString("DeleteRoleSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف المستخدم بنجاح.
        /// </summary>
        public static string DeleteUserSucceeded {
            get {
                return ResourceManager.GetString("DeleteUserSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا تتطابق.
        /// </summary>
        public static string DoesnotMatch_F {
            get {
                return ResourceManager.GetString("DoesnotMatch_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات مستخدم.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني غير مسجل.
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موظف.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا لم يتم الحفظ حيث أن حجم الصورة تعدي 4 ميجا بايت.
        /// </summary>
        public static string FailedToSave_ImageSize_Max_4_MB {
            get {
                return ResourceManager.GetString("FailedToSave_ImageSize_Max_4_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا لم يتم التغيير حيث أن الصورة غير صالحة.
        /// </summary>
        public static string FailedToSave_InvalidPic {
            get {
                return ResourceManager.GetString("FailedToSave_InvalidPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنثى.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاول.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت.
        /// </summary>
        public static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم بالكامل.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميلادي.
        /// </summary>
        public static string GregorianDate {
            get {
                return ResourceManager.GetString("GregorianDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هجري.
        /// </summary>
        public static string HijriDate {
            get {
                return ResourceManager.GetString("HijriDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انا لست برنامج روبوت.
        /// </summary>
        public static string IamNotARobot {
            get {
                return ResourceManager.GetString("IamNotARobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية.
        /// </summary>
        public static string IdentityNumber {
            get {
                return ResourceManager.GetString("IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مفعل.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون باللغة الإنجليزية.
        /// </summary>
        public static string InEnglishLetters {
            get {
                return ResourceManager.GetString("InEnglishLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاستعلام عن تذكرة.
        /// </summary>
        public static string InquireAboutTicket {
            get {
                return ResourceManager.GetString("InquireAboutTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حدث خطأ أثناء التحميل.
        /// </summary>
        public static string InternalErrorWhileLoading {
            get {
                return ResourceManager.GetString("InternalErrorWhileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير صحيح.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ غير صحيح.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابط لم يعد صالحاً للإستخدام.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من ذوي الإحتياجات الخاصة.
        /// </summary>
        public static string IsSpecialNeeds {
            get {
                return ResourceManager.GetString("IsSpecialNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر تحديث.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان يكون 10 ارقام.
        /// </summary>
        public static string Length_10 {
            get {
                return ResourceManager.GetString("Length_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يجب ان يتجاوز 100 حرف.
        /// </summary>
        public static string Max_100 {
            get {
                return ResourceManager.GetString("Max_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يجب ان يتجاوز 15 حرف.
        /// </summary>
        public static string Max_15 {
            get {
                return ResourceManager.GetString("Max_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يجب ان يتجاوز 150 حرف.
        /// </summary>
        public static string Max_150 {
            get {
                return ResourceManager.GetString("Max_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يجب ان يتجاوز 300 حرف.
        /// </summary>
        public static string Max_300 {
            get {
                return ResourceManager.GetString("Max_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يجب ان يتجاوز 50 حرف.
        /// </summary>
        public static string Max_50 {
            get {
                return ResourceManager.GetString("Max_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يجب ان يتجاوز 500 حرف.
        /// </summary>
        public static string Max_500 {
            get {
                return ResourceManager.GetString("Max_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ارسال رسالة على البريد الألكتروني.
        /// </summary>
        public static string MessageSentToEmail {
            get {
                return ResourceManager.GetString("MessageSentToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تكون 6 خانات أو أكثر.
        /// </summary>
        public static string MinLength_6 {
            get {
                return ResourceManager.GetString("MinLength_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار الصلاحية.
        /// </summary>
        public static string MustSelectClaim {
            get {
                return ResourceManager.GetString("MustSelectClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحدث.
        /// </summary>
        public static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك صلاحية للوصول إلى تلك الصفحة.
        /// </summary>
        public static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بيانات.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مسجل.
        /// </summary>
        public static string NotRegistered {
            get {
                return ResourceManager.GetString("NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأقدم.
        /// </summary>
        public static string Oldest {
            get {
                return ResourceManager.GetString("Oldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أو.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تحتوي كلمة المرور على التالي.
        /// </summary>
        public static string PasswordMustHasTheFollowing {
            get {
                return ResourceManager.GetString("PasswordMustHasTheFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الشخصية.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسجل من قبل.
        /// </summary>
        public static string PreviouslyRegistered {
            get {
                return ResourceManager.GetString("PreviouslyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        public static string RegisterLogin {
            get {
                return ResourceManager.GetString("RegisterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التسجيل بنجاح.
        /// </summary>
        public static string RegisterSucceeded {
            get {
                return ResourceManager.GetString("RegisterSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التسجيل.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرني.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجباري.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فضلاً أدخل البيانات المطلوبة.
        /// </summary>
        public static string RequiredDataNotInserted {
            get {
                return ResourceManager.GetString("RequiredDataNotInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعادة تعيين كلمة المرور.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اعادة تعيين كلمة المرور بنجاح.
        /// </summary>
        public static string ResetPasswordSucceededMsg {
            get {
                return ResourceManager.GetString("ResetPasswordSucceededMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد النتائج.
        /// </summary>
        public static string ResultsCount {
            get {
                return ResourceManager.GetString("ResultsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استرجاع.
        /// </summary>
        public static string Retrieval {
            get {
                return ResourceManager.GetString("Retrieval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العودة إلى.
        /// </summary>
        public static string ReturnTo {
            get {
                return ResourceManager.GetString("ReturnTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دور.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الدور.
        /// </summary>
        public static string RoleDetails {
            get {
                return ResourceManager.GetString("RoleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدور.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الادوار.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعذر الحفظ.
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء حفظ الدور.
        /// </summary>
        public static string SaveRoleFailed {
            get {
                return ResourceManager.GetString("SaveRoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ الدور بنجاح.
        /// </summary>
        public static string SaveRoleSucceeded {
            get {
                return ResourceManager.GetString("SaveRoleSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- اختر ---.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال رسالتك بنجاح.
        /// </summary>
        public static string SendDone {
            get {
                return ResourceManager.GetString("SendDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً، فشل ارسال رسالة على البريد الألكتروني لذا يرجى المحاولة مرة اخرى.
        /// </summary>
        public static string SendMsgToEmailFailed {
            get {
                return ResourceManager.GetString("SendMsgToEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الخدمة.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف المختصر.
        /// </summary>
        public static string ShortDesc {
            get {
                return ResourceManager.GetString("ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان يبدأ بـ 05.
        /// </summary>
        public static string StartWith_05 {
            get {
                return ResourceManager.GetString("StartWith_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغلق.
        /// </summary>
        public static string State_Closed {
            get {
                return ResourceManager.GetString("State_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري العمل.
        /// </summary>
        public static string State_In_progress {
            get {
                return ResourceManager.GetString("State_In_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد.
        /// </summary>
        public static string State_New {
            get {
                return ResourceManager.GetString("State_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد الانتظار.
        /// </summary>
        public static string State_On_Hold {
            get {
                return ResourceManager.GetString("State_On_Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحل.
        /// </summary>
        public static string State_Resolved {
            get {
                return ResourceManager.GetString("State_Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف الفرعي.
        /// </summary>
        public static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدعم الفني.
        /// </summary>
        public static string TechSupport {
            get {
                return ResourceManager.GetString("TechSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط والأحكام.
        /// </summary>
        public static string Terms_Conditions {
            get {
                return ResourceManager.GetString("Terms_Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ال.
        /// </summary>
        public static string The {
            get {
                return ResourceManager.GetString("The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلاغ.
        /// </summary>
        public static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصنيف البلاغ.
        /// </summary>
        public static string TicketCategory {
            get {
                return ResourceManager.GetString("TicketCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم البلاغ.
        /// </summary>
        public static string TicketNo {
            get {
                return ResourceManager.GetString("TicketNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بلاغ بهذا الرقم.
        /// </summary>
        public static string TicketNotExist {
            get {
                return ResourceManager.GetString("TicketNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم البلاغ.
        /// </summary>
        public static string TicketNumber {
            get {
                return ResourceManager.GetString("TicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصنيف البلاغ الفرعي.
        /// </summary>
        public static string TicketSubCategory {
            get {
                return ResourceManager.GetString("TicketSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود التعريفي.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إضافة التعليق بنجاح للطلب رقم .
        /// </summary>
        public static string UpdateTicketSucceeded {
            get {
                return ResourceManager.GetString("UpdateTicketSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الدخول غير صحيحة ، من فضلك تأكد من رقم الهوية وكلمة المرور.
        /// </summary>
        public static string User_InvalidCredentials {
            get {
                return ResourceManager.GetString("User_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحباً.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
